// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbybAIvMKvZZO0xVw0debIiBUDqkpydcclYD3U76qf19SnaiT8-SHEeDVCzDLwAJdD8J/exec";
